name: Markdown-HTML

on:
  push:
    branches: master
jobs:
  dewitt:
    name: deploydoc
    runs-on: ubuntu-latest
    steps:
      - name: Create PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.0.1
        input_dir: raw
        output_dir: output
        build_html: true
