name: Markdown-HTML

on:
  push:
    branches: master
    paths:
      - 'raw/**.md'
jobs:
  dewitt:
    name: deploydoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf
        with:
          input_dir: raw
          output_dir: output
          build_html: true
      - uses: actions/upload-artifact
        with:
          name: raw
          path: output
