name: Markdown-HTML
uses: ZacJW/markdown-html-action@1.1.0
  with:
          input_files: '["wildcard*.md"]'
          output_files: '"final_document.html"'
          builtin_stylesheet: 'style.css'
          packages: 'pymdown-extensions'
          extensions: '["pymdownx.extra"]'
